#!/bin/bash
readonly RED="\e[31m"
readonly YELLOW="\e[33m"
readonly GREEN="\e[32m"
readonly STD="\e[0m"

if [ $# -lt 1 ]
  then
    echo -e "${RED}Error! Too few arguments supplied!"
    echo -e "${STD}Command: docker-del-nginx <container-name>"
    exit 1
fi

HNAME=$1

# Remove the container
echo -e "${YELLOW}Removing the container ${HNAME}...${STD}"
read -r -p "Are you sure? [y/N] " response
response=${response,,}
if [[ $response =~ ^(yes|y)$ ]]
  then
    docker rm -f $1
    echo -e "${GREEN}Container ${HNAME} removed${STD}"
  else
    echo -e "${STD}nothing deleted"
    exit 0
fi

# Remove the nginx data
echo -e "${YELLOW}Removing the nginx folders...${STD}"
rm -r /etc/nginx
rm -r /var/log/nginx
echo -e "${GREEN}Folders removed${STD}"
